baseURL = "https://micro.tylucie.fr/"
languageCode = "en-us"
title = "ğŸ¡ Micro Lucie"
theme = "term"
enableRobotsTXT = true
canonifyURLs = false
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[params]
  textFont = 'Source Code Pro'
  footer = 'ğŸŒ² Please consider the environment before printing this website'

[params.social]
  email = "hello@yannickschutz.com"

[params.fathom]
  host = "logs.vadrouilles.co"
  siteID = "IMJQP"
