baseURL = "https://micro.tylucie.fr/"
languageCode = "en-us"
title = "ğŸ¡ Micro Lucie"
theme = "term"
enableRobotsTXT = true
canonifyURLs = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  footer = 'ğŸŒ² Please consider the environment before printing this website'

[params.social]
  email = "yannick@tylucie.fr"

[params.fathom]
  host = "logs.vadrouilles.co"
  siteID = "IMJQP"

[permalinks]
  posts = "/:slug"
